# Generated by Django 3.2.15 on 2023-10-18 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20231019_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='szu',
            name='amper',
            field=models.DecimalField(choices=[(0.5, '0.5'), (1, '1'), (2, '2'), (2.1, '2.1'), (3, '3')], decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='szu',
            name='brand',
            field=models.ForeignKey(default='без бренда', help_text='Бренд', max_length=100, on_delete=django.db.models.deletion.PROTECT, to='posts.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='szuusb',
            name='amper',
            field=models.DecimalField(choices=[(0.5, '0.5'), (1, '1'), (2, '2'), (2.1, '2.1'), (3, '3')], decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='szuusb',
            name='brand',
            field=models.ForeignKey(default='без бренда', help_text='Бренд', max_length=100, on_delete=django.db.models.deletion.PROTECT, to='posts.brand', verbose_name='Бренд'),
        ),
    ]
