# Generated by Django 3.2.15 on 2023-10-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20231019_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='szu',
            name='color',
            field=models.CharField(blank=True, choices=[('red', 'красный'), ('blue', 'синий'), ('green', 'зеленый'), ('white', 'белый'), ('black', 'черный')], default='нет', help_text='Цвет', max_length=100, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='szuusb',
            name='color',
            field=models.CharField(blank=True, choices=[('red', 'красный'), ('blue', 'синий'), ('green', 'зеленый'), ('white', 'белый'), ('black', 'черный')], default='нет', help_text='Цвет', max_length=100, null=True, verbose_name='Цвет'),
        ),
    ]
