# Generated by Django 3.2.15 on 2023-10-18 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20231019_0144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='szu',
            options={'verbose_name': 'СЗУ', 'verbose_name_plural': 'СЗУ'},
        ),
        migrations.AlterModelOptions(
            name='szuusb',
            options={'verbose_name': 'СЗУ-USB', 'verbose_name_plural': 'СЗУ-USB'},
        ),
    ]
