# Generated by Django 3.2.15 on 2023-10-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20231019_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='szu',
            name='amper',
            field=models.FloatField(choices=[(0.5, '0.5'), (1.0, '1'), (2.0, '2'), (2.1, '2.1'), (3.0, '3'), (4.0, '4')]),
        ),
        migrations.AlterField(
            model_name='szuusb',
            name='amper',
            field=models.FloatField(choices=[(0.5, '0.5'), (1.0, '1'), (2.0, '2'), (2.1, '2.1'), (3.0, '3'), (4.0, '4')]),
        ),
    ]
