# Generated by Django 3.2.15 on 2023-10-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_azu_azuusb_datacabel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datacabel',
            options={'verbose_name': 'Дата-кабель', 'verbose_name_plural': 'Дата-кабели'},
        ),
        migrations.AddField(
            model_name='datacabel',
            name='amper',
            field=models.FloatField(choices=[(0.5, '0.5'), (1.0, '1'), (2.0, '2'), (2.1, '2.1'), (3.0, '3'), (4.0, '4'), (5.0, '5')], default=5),
            preserve_default=False,
        ),
    ]
