# Generated by Django 4.2.6 on 2023-10-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20231019_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azu',
            name='charger_type',
            field=models.CharField(choices=[('Micro USB', 'Micro USB'), ('USB-C', 'USB-C'), ('Lightning', 'Lightning'), ('Mini USB', 'Mini USB'), ('Samsung D880', 'Samsung D880'), ('Nokia 6101', 'Nokia 6101')], max_length=20),
        ),
        migrations.AlterField(
            model_name='azu',
            name='color',
            field=models.CharField(blank=True, choices=[('красный', 'красный'), ('синий', 'синий'), ('зеленый', 'зеленый'), ('белый', 'белый'), ('черный', 'черный')], default='нет', help_text='Цвет', max_length=100, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='azuusb',
            name='color',
            field=models.CharField(blank=True, choices=[('красный', 'красный'), ('синий', 'синий'), ('зеленый', 'зеленый'), ('белый', 'белый'), ('черный', 'черный')], default='нет', help_text='Цвет', max_length=100, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='datacabel',
            name='charger_type',
            field=models.CharField(choices=[('Micro USB', 'Micro USB'), ('USB-C', 'USB-C'), ('Lightning', 'Lightning'), ('Mini USB', 'Mini USB'), ('Samsung D880', 'Samsung D880'), ('Nokia 6101', 'Nokia 6101')], max_length=20),
        ),
        migrations.AlterField(
            model_name='datacabel',
            name='color',
            field=models.CharField(blank=True, choices=[('красный', 'красный'), ('синий', 'синий'), ('зеленый', 'зеленый'), ('белый', 'белый'), ('черный', 'черный')], default='нет', help_text='Цвет', max_length=100, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='headphones',
            name='color',
            field=models.CharField(blank=True, choices=[('красный', 'красный'), ('синий', 'синий'), ('зеленый', 'зеленый'), ('белый', 'белый'), ('черный', 'черный')], default='нет', help_text='Цвет', max_length=100, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='szu',
            name='charger_type',
            field=models.CharField(choices=[('Micro USB', 'Micro USB'), ('USB-C', 'USB-C'), ('Lightning', 'Lightning'), ('Mini USB', 'Mini USB'), ('Samsung D880', 'Samsung D880'), ('Nokia 6101', 'Nokia 6101')], max_length=20),
        ),
        migrations.AlterField(
            model_name='szu',
            name='color',
            field=models.CharField(blank=True, choices=[('красный', 'красный'), ('синий', 'синий'), ('зеленый', 'зеленый'), ('белый', 'белый'), ('черный', 'черный')], default='нет', help_text='Цвет', max_length=100, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='szuusb',
            name='color',
            field=models.CharField(blank=True, choices=[('красный', 'красный'), ('синий', 'синий'), ('зеленый', 'зеленый'), ('белый', 'белый'), ('черный', 'черный')], default='нет', help_text='Цвет', max_length=100, null=True, verbose_name='Цвет'),
        ),
    ]
